FROM frolvlad/alpine-glibc

RUN apk update && apk upgrade && apk add bash && apk add tzdata

RUN cp /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime && echo "Europe/Amsterdam" > /etc/timezone

WORKDIR /

COPY bin/gravity-linux-amd64 /gravity

CMD /gravity -config=/etc/gravity/config.toml